#pragma once
#include "CodexTypes.h"

namespace codex {

enum CardId : uint8_t {
  CARD_STRIKE = 0,
  CARD_DEFEND,
  CARD_BLOT,
  CARD_POMMEL,
  CARD_RIPOSTE,
  CARD_IRON_AEGIS,
  CARD_SPELLBLADE,
  CARD_RUNIC_BARRIER,
  CARD_BLOOD_INK,
  CARD_POISON_QUILL,
  CARD_FLURRY,
  CARD_SANCTUARY,
  CARD_HEX_FRAILTY,
  CARD_LITANY_FIRE,
  CARD_BATTLE_FOCUS,
  CARD_FORTIFY,
  CARD_EXECUTION,
  CARD_CORROSIVE_ACID,
  CARD_BULWARK,
  CARD_BLOOD_RITE,
  CARD_POWER_FURY,
  CARD_POWER_BASTION,
  CARD_POWER_FLOW,
  CARD_SEVER,
  CARD_PARRY_THRUST,
  CARD_DIVINE_AEGIS,
  CARD_REBOUND_WARD,
  CARD_INK_SIPHON,
  CARD_TRANSCENDENCE,
  CARD_TRANSCRIBE,
  CARD_COUNT
};

static constexpr CardDef kCardCatalog[CARD_COUNT] = {
    // id, name, cost, meter, type, effect, baseValue, coupletCond, coupletBonus, desc, coupletDesc
    {CARD_STRIKE, "Rapier Thrust", 1, Meter::Blade, CardType::Attack, CardEffect::Damage, 6, CoupletType::AfterBlade, 3,
     "Deal 6 damage.", "+3 dmg"},
    {CARD_DEFEND, "Parchment Ward", 1, Meter::Ward, CardType::Skill, CardEffect::Block, 5, CoupletType::AfterWard, 3,
     "Gain 5 Ward.", "+3 Ward"},
    {CARD_BLOT, "Blot Out", 0, Meter::Script, CardType::Skill, CardEffect::BlotCard, 3, CoupletType::AfterScript, 1,
     "Draw 2 cards. Gain 3 Ward.", "Refund 1 Ink"},
    {CARD_POMMEL, "Heavy Pommel", 2, Meter::Blade, CardType::Attack, CardEffect::Damage, 12, CoupletType::AfterBlade, 4,
     "Deal 12 damage.", "+4 dmg"},
    {CARD_RIPOSTE, "Riposte", 1, Meter::Blade, CardType::Attack, CardEffect::Damage, 7, CoupletType::AfterWard, 5,
     "Deal 7 damage.", "+5 dmg"},
    {CARD_IRON_AEGIS, "Iron Aegis", 1, Meter::Ward, CardType::Skill, CardEffect::Block, 7, CoupletType::AfterBlade, 4,
     "Gain 7 Ward.", "+4 Ward"},
    {CARD_SPELLBLADE, "Spellblade", 1, Meter::Blade, CardType::Attack, CardEffect::Damage, 6, CoupletType::AfterScript,
     1,  // 1 bonus ink
     "Deal 6 damage.", "Refund 1 Ink"},
    {CARD_RUNIC_BARRIER, "Runic Barrier", 2, Meter::Ward, CardType::Skill, CardEffect::Block, 11,
     CoupletType::AfterScript, 2,  // 2 weak
     "Gain 11 Ward.", "Apply 2 Weak"},
    {CARD_BLOOD_INK, "Blood Ink", 0, Meter::Script, CardType::Skill, CardEffect::BloodInk, 2, CoupletType::None, 0,
     "Lose 3 HP. Gain 2 Ink.", nullptr},
    {CARD_POISON_QUILL, "Poisoned Quill", 1, Meter::Script, CardType::Attack, CardEffect::ApplyPoison, 4,
     CoupletType::AfterBlade, 3, "Deal 4 dmg. Apply 4 Poison.", "+3 Poison"},
    {CARD_FLURRY, "Flurry", 1, Meter::Blade, CardType::Attack, CardEffect::Damage, 3, CoupletType::AfterBlade,
     3,  // hits 3 times instead of 2
     "Deal 3 damage twice (6).", "Strikes 3x"},
    {CARD_SANCTUARY, "Sanctuary", 2, Meter::Ward, CardType::Skill, CardEffect::Block, 14, CoupletType::None, 0,
     "Gain 14 Ward.", nullptr},
    {CARD_HEX_FRAILTY, "Hex of Frailty", 1, Meter::Script, CardType::Skill, CardEffect::ApplyWeak, 2, CoupletType::None,
     0, "Apply 2 Weak and 2 Vulnerable.", nullptr},
    {CARD_LITANY_FIRE, "Litany of Fire", 2, Meter::Script, CardType::Attack, CardEffect::Damage, 14,
     CoupletType::AfterBlade, 6, "Deal 14 damage.", "+6 dmg"},
    {CARD_BATTLE_FOCUS, "Battle Focus", 0, Meter::Script, CardType::Skill, CardEffect::DrawCards, 3, CoupletType::None,
     0, "Draw 3 cards.", nullptr},
    {CARD_FORTIFY, "Fortify", 1, Meter::Ward, CardType::Skill, CardEffect::Block, 8, CoupletType::AfterWard, 4,
     "Gain 8 Ward.", "+4 Ward"},
    {CARD_EXECUTION, "Execution", 2, Meter::Blade, CardType::Attack, CardEffect::Damage, 16, CoupletType::None, 0,
     "Deal 16 damage.", nullptr},
    {CARD_CORROSIVE_ACID, "Corrosive Acid", 1, Meter::Script, CardType::Attack, CardEffect::ApplyVulnerable, 6,
     CoupletType::None, 0, "Deal 6 dmg. Apply 2 Vulnerable.", nullptr},
    {CARD_BULWARK, "Bulwark", 3, Meter::Ward, CardType::Skill, CardEffect::Block, 22, CoupletType::None, 0,
     "Gain 22 Ward.", nullptr},
    {CARD_BLOOD_RITE, "Blood Rite", 1, Meter::Script, CardType::Attack, CardEffect::DamageAndBlock, 9,
     CoupletType::None, 0, "Deal 9 damage. Gain 4 Ward.", nullptr},
    {CARD_POWER_FURY, "Illumination: Fury", 1, Meter::Blade, CardType::Power, CardEffect::PowerStrength, 2,
     CoupletType::None, 0, "Gain +2 Strength for all attacks. [1-Use]", nullptr},
    {CARD_POWER_BASTION, "Illumination: Bastion", 1, Meter::Ward, CardType::Power, CardEffect::PowerRetainWard, 1,
     CoupletType::None, 0, "Ward does not halve at end of turn. [1-Use]", nullptr},
    {CARD_POWER_FLOW, "Illumination: Flow", 1, Meter::Script, CardType::Power, CardEffect::PowerCardDraw, 1,
     CoupletType::None, 0, "Draw +1 card at start of each turn. [1-Use]", nullptr},
    {CARD_SEVER, "Sever", 2, Meter::Blade, CardType::Attack, CardEffect::SeverVulnerable, 14,
     CoupletType::None, 0, "Deal 14 damage. (+10 if Vulnerable)", nullptr},
    {CARD_PARRY_THRUST, "Parry & Thrust", 1, Meter::Blade, CardType::Attack, CardEffect::ParryThrust, 5,
     CoupletType::AfterWard, 4, "Gain 5 Ward. Deal 5 damage.", "+4 dmg"},
    {CARD_DIVINE_AEGIS, "Divine Aegis", 2, Meter::Ward, CardType::Skill, CardEffect::DivineAegis, 15,
     CoupletType::None, 0, "Gain 15 Ward. Retain Ward this turn.", nullptr},
    {CARD_REBOUND_WARD, "Rebound", 1, Meter::Ward, CardType::Skill, CardEffect::ReboundWard, 8,
     CoupletType::AfterBlade, 0, "Gain 8 Ward.", "Deal dmg = Ward (max 12)"},
    {CARD_INK_SIPHON, "Ink Siphon", 1, Meter::Script, CardType::Attack, CardEffect::InkSiphon, 7,
     CoupletType::None, 0, "Deal 7 damage. If Weak, gain 1 Ink.", nullptr},
    {CARD_TRANSCENDENCE, "Illumination: Transcendence", 2, Meter::Script, CardType::Power, CardEffect::PowerTranscendence, 1,
     CoupletType::None, 0, "All Couplet verses always trigger! [1-Use]", nullptr},
    {CARD_TRANSCRIBE, "Transcribe", 0, Meter::Script, CardType::Skill, CardEffect::TranscribeCard, 2,
     CoupletType::None, 0, "Draw 2 cards. Discard 1 card.", nullptr}};

static constexpr RelicDef kRelicCatalog[] = {
    {0, "Silver Quill", "Gain 1 Ink on the first turn of combat."},
    {1, "Iron Sigil", "Start combat with 6 Ward."},
    {2, "Vampiric Seal", "Heal 2 HP after winning a battle."},
    {3, "Scholar's Ring", "Start combat with +1 extra card in hand."},
    {4, "Whetstone", "All Blade attacks deal +1 damage."},
    {5, "Monk's Rosary", "Ward retained between turns does not halve."},
    {6, "Golden Bookmark", "Gain +15 Gold after winning every combat."},
    {7, "Obsidian Inkwell", "Whenever you play 3 Script cards, gain 1 Ink."},
    {8, "Barbed Bookmark", "When an enemy hits your Ward, deal 3 damage back."},
    {9, "Hourglass of Sand", "Every 3 turns, draw 2 additional cards."},
    {10, "Censer of Cleansing", "Remove Weak and Vulnerable at start of turn 2."},
    {11, "Alchemical Flask", "Heal 8 HP whenever you visit a Shop."}
};
constexpr uint8_t RELIC_COUNT = sizeof(kRelicCatalog) / sizeof(kRelicCatalog[0]);

}  // namespace codex
